DROP TABLE IF EXISTS petition;
DROP TABLE IF EXISTS user_profiles;
DROP TABLE IF EXISTS users;

CREATE TABLE users(
id SERIAL PRIMARY KEY,
firstname VARCHAR(200) NOT NULL,
lastname VARCHAR(200) NOT NULL,
email VARCHAR(200) NOT NULL UNIQUE,
password VARCHAR(200) NOT NULL,
ts_user TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE petition(
id SERIAL PRIMARY KEY,
signature TEXT NOT NULL,
user_id INTEGER NOT NULL REFERENCES users(id),
ts_petition TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_profiles(
id SERIAL PRIMARY KEY,
age INTEGER,
city VARCHAR(100),
url VARCHAR(300),
user_id INTEGER NOT NULL UNIQUE REFERENCES users(id),
ts_userprofile TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
